### PR TITLE
fix(binaries): fetch new binaries

### LINKED ISSUE #221: Detect images by OS and Linux distribution instead of by platform
Currently, this is blocked by prisma/prisma-engine#37. After this is done, the detection needs to be refactored.

Instead of just checking the libssl version or platform type, we should check for the operating system and the core distribution like CentOS, Debian, etc. and additionally append the libssl version and download the correct binary.

Idea: if no specific platform for which we have built binaries is detected, I think we should still check the OpenSSL version and default to Debian (maybe log a warning message), because it seems Debian works on most other distributions.

More info at prisma/prisma-engine#37 (binary issue) and prisma/prisma2#533 (umbrella issue)

### PR DESCRIPTION
**Pull request by steebchen**
fix #221

### CODE REVIEW

File: packages/fetch-engine/scripts/test.ts [hunk 1]
```diff
@@ -1,11 +1,11 @@
 import { download } from '../src'
-import path from 'path'
```
Comment (timsuchanek) [inline packages/fetch-engine/scripts/test.ts]: Please keep the import convention of `import path`, as that's how we do it in all codebases.

Comment (steebchen) [reply packages/fetch-engine/scripts/test.ts]: Oh okay, I edited that because it showed an error:

image
